<template>
  <div id="columns">
    <span>{{name}}</span>
    <div  
      v-for="topic in topics"
      :key="topic.id"
      class="grass"
      :style="{
        background: calcGrassColor(topic.progress)
      }"
    >
    <span v-if="topic.progress === 100">!</span>
    </div>
  </div>
</template>

<script>
import * as utils from "../utils";

const endpoint = "https://judgeapi.u-aizu.ac.jp";

export default {
  props: {
    courseData: Object
  },
  data() {
    return {
      name: "ALDS1",
      topics: [
        {
          id: 1,
          serial: 1,
          name: "入門",
          shortName: "ALDS1_1",
          maxScore: 400,
          numberOfProblems: 4,
          userScore: 400,
          progress: 100,
          courseId: 1,
          problems: [
            {
              id: "ALDS1_1_A",
              available: 1,
              doctype: 4,
              name: "Insertion Sort",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 5727,
              submissions: 22198,
              recommendations: 1,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_1_B",
              available: 1,
              doctype: 4,
              name: "Greatest Common Divisor",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 4457,
              submissions: 11398,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_1_C",
              available: 1,
              doctype: 4,
              name: "Prime Numbers",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 3853,
              submissions: 17415,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_1_D",
              available: 1,
              doctype: 4,
              name: "Maximum Profit",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 4219,
              submissions: 20272,
              recommendations: 4,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            }
          ],
          description: ""
        },
        {
          id: 5,
          serial: 2,
          name: "初等的ソート",
          shortName: "ALDS1_2",
          maxScore: 400,
          numberOfProblems: 4,
          userScore: 400,
          progress: 100,
          courseId: 1,
          problems: [
            {
              id: "ALDS1_2_A",
              available: 1,
              doctype: 4,
              name: "Bubble Sort",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 4814,
              submissions: 13369,
              recommendations: 2,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_2_B",
              available: 1,
              doctype: 4,
              name: "Selection Sort",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 4400,
              submissions: 9069,
              recommendations: 2,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_2_C",
              available: 1,
              doctype: 4,
              name: "Stable Sort",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 2966,
              submissions: 8822,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_2_D",
              available: 3,
              doctype: 4,
              name: "Shell Sort",
              problemTimeLimit: 6,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 1727,
              submissions: 8743,
              recommendations: 2,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            }
          ],
          description: ""
        },
        {
          id: 6,
          serial: 3,
          name: "基本データ構造",
          shortName: "ALDS1_3",
          maxScore: 400,
          numberOfProblems: 4,
          userScore: 400,
          progress: 100,
          courseId: 1,
          problems: [
            {
              id: "ALDS1_3_A",
              available: 1,
              doctype: 4,
              name: "Stack",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 4024,
              submissions: 12028,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_3_B",
              available: 1,
              doctype: 4,
              name: "Queue",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 3414,
              submissions: 10520,
              recommendations: 1,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_3_C",
              available: 1,
              doctype: 4,
              name: "Doubly Linked List",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 2310,
              submissions: 17228,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_3_D",
              available: 1,
              doctype: 4,
              name: "Areas on the Cross-Section Diagram",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 1284,
              submissions: 4896,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            }
          ],
          description: ""
        },
        {
          id: 10,
          serial: 4,
          name: "探索",
          shortName: "ALDS1_4",
          maxScore: 400,
          numberOfProblems: 4,
          userScore: 400,
          progress: 100,
          courseId: 1,
          problems: [
            {
              id: "ALDS1_4_A",
              available: 1,
              doctype: 4,
              name: "Linear Search",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 3373,
              submissions: 10250,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_4_B",
              available: 1,
              doctype: 4,
              name: "Binary Search",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 3322,
              submissions: 12150,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_4_C",
              available: 1,
              doctype: 4,
              name: "Dictionary",
              problemTimeLimit: 2,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 2244,
              submissions: 12561,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_4_D",
              available: 1,
              doctype: 4,
              name: "Allocation",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 1302,
              submissions: 5821,
              recommendations: 2,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            }
          ],
          description: ""
        },
        {
          id: 11,
          serial: 5,
          name: "分割統治法",
          shortName: "ALDS1_5",
          maxScore: 400,
          numberOfProblems: 4,
          userScore: 400,
          progress: 100,
          courseId: 1,
          problems: [
            {
              id: "ALDS1_5_A",
              available: 1,
              doctype: 4,
              name: "Exhaustive Search",
              problemTimeLimit: 5,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 2678,
              submissions: 7678,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_5_B",
              available: 1,
              doctype: 4,
              name: "Merge Sort",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 2192,
              submissions: 8073,
              recommendations: 1,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_5_C",
              available: 1,
              doctype: 4,
              name: "Koch Curve",
              problemTimeLimit: 2,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 1715,
              submissions: 4170,
              recommendations: 1,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_5_D",
              available: 1,
              doctype: 4,
              name: "The Number of Inversions",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 936,
              submissions: 4220,
              recommendations: 1,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            }
          ],
          description: ""
        },
        {
          id: 12,
          serial: 6,
          name: "ソート",
          shortName: "ALDS1_6",
          maxScore: 400,
          numberOfProblems: 4,
          userScore: 300,
          progress: 75,
          courseId: 1,
          problems: [
            {
              id: "ALDS1_6_A",
              available: 1,
              doctype: 4,
              name: "Counting Sort",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 1864,
              submissions: 8056,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_6_B",
              available: 1,
              doctype: 4,
              name: "Partition",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 2006,
              submissions: 4222,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_6_C",
              available: 1,
              doctype: 4,
              name: "Quick Sort",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 1446,
              submissions: 5531,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_6_D",
              available: 1,
              doctype: 4,
              name: "Minimum Cost Sort",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 548,
              submissions: 1901,
              recommendations: 0,
              isSolved: false,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 0
            }
          ],
          description: ""
        },
        {
          id: 14,
          serial: 7,
          name: "木構造",
          shortName: "ALDS1_7",
          maxScore: 400,
          numberOfProblems: 4,
          userScore: 300,
          progress: 75,
          courseId: 1,
          problems: [
            {
              id: "ALDS1_7_A",
              available: 1,
              doctype: 4,
              name: "Rooted Trees",
              problemTimeLimit: 2,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 1775,
              submissions: 7944,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_7_B",
              available: 1,
              doctype: 4,
              name: "Binary Trees",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 1590,
              submissions: 5527,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_7_C",
              available: 1,
              doctype: 4,
              name: "Tree Walk",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 1475,
              submissions: 3861,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_7_D",
              available: 1,
              doctype: 4,
              name: "Reconstruction of a Tree",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 680,
              submissions: 1608,
              recommendations: 0,
              isSolved: false,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 0
            }
          ],
          description: ""
        },
        {
          id: 17,
          serial: 8,
          name: "二分探索木",
          shortName: "ALDS1_8",
          maxScore: 400,
          numberOfProblems: 4,
          userScore: 300,
          progress: 75,
          courseId: 1,
          problems: [
            {
              id: "ALDS1_8_A",
              available: 1,
              doctype: 4,
              name: "Binary Search Tree I",
              problemTimeLimit: 2,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 1698,
              submissions: 4968,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_8_B",
              available: 1,
              doctype: 4,
              name: "Binary Search Tree II",
              problemTimeLimit: 2,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 1595,
              submissions: 3147,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_8_C",
              available: 1,
              doctype: 4,
              name: "Binary Search Tree III",
              problemTimeLimit: 2,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 1216,
              submissions: 4000,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_8_D",
              available: 1,
              doctype: 4,
              name: "Treap",
              problemTimeLimit: 2,
              problemMemoryLimit: 262144,
              maxScore: 100,
              solvedUser: 92,
              submissions: 186,
              recommendations: 0,
              isSolved: false,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 0
            }
          ],
          description: ""
        },
        {
          id: 18,
          serial: 9,
          name: "ヒープ",
          shortName: "ALDS1_9",
          maxScore: 300,
          numberOfProblems: 3,
          userScore: 260,
          progress: 86.66666666666667,
          courseId: 1,
          problems: [
            {
              id: "ALDS1_9_A",
              available: 1,
              doctype: 4,
              name: "Complete Binary Tree",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 1681,
              submissions: 4977,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_9_B",
              available: 1,
              doctype: 4,
              name: "Maximum Heap",
              problemTimeLimit: 2,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 1580,
              submissions: 4416,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_9_C",
              available: 1,
              doctype: 4,
              name: "Priority Queue",
              problemTimeLimit: 2,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 1374,
              submissions: 5706,
              recommendations: 0,
              isSolved: false,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 60
            }
          ],
          description: ""
        },
        {
          id: 19,
          serial: 10,
          name: "動的計画法",
          shortName: "ALDS1_10",
          maxScore: 400,
          numberOfProblems: 4,
          userScore: 100,
          progress: 25,
          courseId: 1,
          problems: [
            {
              id: "ALDS1_10_A",
              available: 1,
              doctype: 4,
              name: "Fibonacci Number",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 2349,
              submissions: 5433,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_10_B",
              available: 1,
              doctype: 4,
              name: "Matrix Chain Multiplication",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 1486,
              submissions: 3336,
              recommendations: 0,
              isSolved: false,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 0
            },
            {
              id: "ALDS1_10_C",
              available: 1,
              doctype: 4,
              name: "Longest Common Subsequence",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 1613,
              submissions: 6934,
              recommendations: 0,
              isSolved: false,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 0
            },
            {
              id: "ALDS1_10_D",
              available: 2,
              doctype: 4,
              name: "Optimal Binary Search Tree",
              problemTimeLimit: 2,
              problemMemoryLimit: 262144,
              maxScore: 100,
              solvedUser: 14,
              submissions: 44,
              recommendations: 0,
              isSolved: false,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 0
            }
          ],
          description: ""
        },
        {
          id: 20,
          serial: 11,
          name: "グラフI",
          shortName: "ALDS1_11",
          maxScore: 400,
          numberOfProblems: 4,
          userScore: 100,
          progress: 25,
          courseId: 1,
          problems: [
            {
              id: "ALDS1_11_A",
              available: 1,
              doctype: 4,
              name: "Graph",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 2141,
              submissions: 5134,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_11_B",
              available: 1,
              doctype: 4,
              name: "Depth First Search",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 1907,
              submissions: 5252,
              recommendations: 0,
              isSolved: false,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 0
            },
            {
              id: "ALDS1_11_C",
              available: 1,
              doctype: 4,
              name: "Breadth First Search",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 1515,
              submissions: 3903,
              recommendations: 0,
              isSolved: false,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 0
            },
            {
              id: "ALDS1_11_D",
              available: 1,
              doctype: 4,
              name: "Connected Components",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 776,
              submissions: 3657,
              recommendations: 0,
              isSolved: false,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 0
            }
          ],
          description: ""
        },
        {
          id: 21,
          serial: 12,
          name: "グラフII",
          shortName: "ALDS1_12",
          maxScore: 300,
          numberOfProblems: 3,
          userScore: 100,
          progress: 33.333333333333336,
          courseId: 1,
          problems: [
            {
              id: "ALDS1_12_A",
              available: 1,
              doctype: 4,
              name: "Minimum Spanning Tree",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 1609,
              submissions: 3966,
              recommendations: 0,
              isSolved: true,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 100
            },
            {
              id: "ALDS1_12_B",
              available: 1,
              doctype: 4,
              name: "Single Source Shortest Path I",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 1441,
              submissions: 3459,
              recommendations: 0,
              isSolved: false,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 0
            },
            {
              id: "ALDS1_12_C",
              available: 1,
              doctype: 4,
              name: "Single Source Shortest Path II",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 746,
              submissions: 3095,
              recommendations: 0,
              isSolved: false,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 0
            }
          ],
          description: ""
        },
        {
          id: 41,
          serial: 13,
          name: "ヒューリスティック探索",
          shortName: "ALDS1_13",
          maxScore: 300,
          numberOfProblems: 3,
          userScore: 0,
          progress: 0,
          courseId: 1,
          problems: [
            {
              id: "ALDS1_13_A",
              available: 1,
              doctype: 4,
              name: "8 Queens Problem",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 695,
              submissions: 1592,
              recommendations: 0,
              isSolved: false,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 0
            },
            {
              id: "ALDS1_13_B",
              available: 1,
              doctype: 4,
              name: "8 Puzzle",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 428,
              submissions: 2036,
              recommendations: 0,
              isSolved: false,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 0
            },
            {
              id: "ALDS1_13_C",
              available: 1,
              doctype: 4,
              name: "15 Puzzle",
              problemTimeLimit: 3,
              problemMemoryLimit: 262144,
              maxScore: 100,
              solvedUser: 262,
              submissions: 2063,
              recommendations: 0,
              isSolved: false,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 0
            }
          ],
          description: ""
        },
        {
          id: 45,
          serial: 14,
          name: "文字列検索",
          shortName: "ALDS1_14",
          maxScore: 400,
          numberOfProblems: 4,
          userScore: 0,
          progress: 0,
          courseId: 1,
          problems: [
            {
              id: "ALDS1_14_A",
              available: 1,
              doctype: 4,
              name: "Naive String Search",
              problemTimeLimit: 1,
              problemMemoryLimit: 131072,
              maxScore: 100,
              solvedUser: 376,
              submissions: 683,
              recommendations: 0,
              isSolved: false,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 0
            },
            {
              id: "ALDS1_14_B",
              available: 1,
              doctype: 4,
              name: "String Search",
              problemTimeLimit: 1,
              problemMemoryLimit: 262144,
              maxScore: 100,
              solvedUser: 260,
              submissions: 1831,
              recommendations: 0,
              isSolved: false,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 0
            },
            {
              id: "ALDS1_14_C",
              available: 1,
              doctype: 4,
              name: "Pattern Search",
              problemTimeLimit: 3,
              problemMemoryLimit: 262144,
              maxScore: 100,
              solvedUser: 95,
              submissions: 676,
              recommendations: 0,
              isSolved: false,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 0
            },
            {
              id: "ALDS1_14_D",
              available: 1,
              doctype: 4,
              name: "Multiple String Matching",
              problemTimeLimit: 3,
              problemMemoryLimit: 262144,
              maxScore: 100,
              solvedUser: 109,
              submissions: 1477,
              recommendations: 0,
              isSolved: false,
              bookmark: false,
              recommend: false,
              successRate: 0,
              score: 0,
              userScore: 0
            }
          ],
          description: ""
        }
      ]
    };
  },
  methods: {
    calcGrassColor(progress) {
      const hsv = utils.calcGrassColor(progress);
      const rgb = utils.hsvToRGB(hsv);
      return utils.rgbToString(rgb);
    }
  },
  created() {
    console.log(utils.calcGrassColor(0));
    // fetch(`${endpoint}/course/${this.courseData.id}?lang=jp`, {
    //   method: "GET",
    //   mode: "cors",
    //   credentials: "include"
    // })
    //   .then(res => res.json())
    //   .then(data => console.log(data))
    //   // .then(data => {
    //   //   this.name = data.shortName;
    //   //   this.topics = data.topics;
    //   // })
    //   .catch(err => console.error(err));
  }
};
</script>

<style scoped>
#columns {
  display: flex;
  flex-direction: row;
}

.grass {
  width: 16px;
  height: 16px;
  margin: 1px;
  color: white;
  text-align: center;
  border: black 1px solid;
  box-sizing: border-box;
}
</style>
